spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/vending_machine?characterEncoding=utf8&serverTimezone=UTC
    username: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
mybatis:
      mapper-locations: classpath:mapper/*.xml